services:  
  stock-publisher:
    image: manuelbrunner/stock-publisher:v1.0
    container_name: stock-publisher
    restart: always
    environment:
      RABBITMQ_URL: "${RABBITMQ_URL}"
      TICKER_INTERVAL: "${TICKER_INTERVAL}"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - PvsNetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s
    networks:
      - PvsNetwork

# - > stock-consumer-aapl:

# - > stock-consumer-msft:

# - > stock-consumer-tsla:

  mongo1:
    image: mongo:7.0
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./mongo1_data:/data/db"
      - "./mongo1_config:/data/configdb"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s

networks:
 PvsNetwork:
   driver: bridge
